#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# First socat take beast data and sends to standard output
# pv (pipe viewer) shows stats about the transfer every 900 seconds
# Second socat reads from standard input and sends to rawflight

socat -d -d -u TCP:"$BEASTHOST":"$BEASTPORT" - | \
pv -t -r -b -f -N statistics -c --interval 900 | \
socat -d -d -u - TCP:"$RAWFLIGHTHOST":"$RAWFLIGHTPORT"

sleep 3
