#!/usr/bin/with-contenv bash
# shellcheck shell=bash

socat -d -d -u TCP:"$BEASTHOST":"$BEASTPORT" TCP:"$RAWFLIGHTHOST":"$RAWFLIGHTPORT" \
  2>&1 | stdbuf -o0 awk '{print "[rawflight] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 3
